feat: Simple rich text editor component for education & experience description
pingSubhajit/letraz pull request #13
Opened 2024-10-23 05:12 UTC by sahilverma-dev

## Issue
[LET-12 Simple rich text editor component for education & experience description](https://linear.app/letraz/issue/LET-12/feat-simple-rich-text-editor-component-for-education-and-experience)

### Description

This PR implements a rich text editor using the Tiptap library, utilizing its starter kit along with extensions for underline text, bullet points, numbered lists, and links. Additionally, the Shadcn popover component has been imported and installed to enhance the user interface.

### Implemented changes

- Implemented Tiptap for rich text editor
- Created a rich text editor component with  bold, italic, underline text, bullet points, numbered lists, and links
- Integrated rich text editor into education & experience description field in onboarding screens

### Closing Note

The rich text editor is functional as required; however, there are some style changes needed to improve the overall appearance and user experience.

2024-10-27 06:38 UTC, sourabhrathourr requested changes
There's a ux behaviour we can improve right now. When we press `-` and space to trigger markdown lists, `placeholder` comes there as you can see in the below recording. I'm not sure whether this is intentional or not, but this not not something which I feel is a good ux. What say @pingSubhajit ?

Also as you can see in the recording below, whenever we start writing something in lists, it shifts slightly upwards, we can improve this behaviour too.

https://github.com/user-attachments/assets/20317d6b-24c8-49cd-ad97-551c52054c69

2024-10-27 06:38 UTC, sourabhrathourr commented on components/onboarding/RichTextEditor.tsx
> +						className="min-h-40"
We can give some padding to the Editor content because right now if we right something in bullet points or even ordered list, the text is getting clipped slightly. Also what I think is the font size right now for a description seems little high, maybe we can lower it down for better experience.

<img width="537" alt="image" src="https://github.com/user-attachments/assets/debc4b3a-e429-4ee2-86ea-46ca25649152">

2024-10-27 06:38 UTC, sourabhrathourr commented on components/onboarding/RichTextEditor.tsx
> +				<Popover>
I was not able to add links to the description field using this popover.

2024-10-27 06:38 UTC, sourabhrathourr commented on components/onboarding/RichTextEditor.tsx
> +			<ScrollArea className="w-full h-full max-h-52">
Although this is wrapped in `<ScrollArea>` the scrolling doesn't work right now, even if I explicitly give `overflow-y-auto` for some reason, scrolling was not happening (though I saw a scrollbar this time). We would need to debug further about the issue.

2024-10-27 11:35 UTC, sahilverma-dev commented on components/onboarding/RichTextEditor.tsx
> +						className="min-h-40"
Ok, got it I'll improve this.

2024-10-27 11:45 UTC, sahilverma-dev commented on components/onboarding/RichTextEditor.tsx
> +				<Popover>
https://github.com/user-attachments/assets/01954f77-717c-4305-804e-b9fd1d72c23e
Right now, users can add links by selecting text. We can enhance this feature by:

- Implementing link validation
- Introducing a `Link` placeholder that users can customize
- Creating a new popover for editing links when link is selected
- Remove link form the text

Please let me know if I’ve overlooked anything.

2024-10-27 11:48 UTC, sahilverma-dev commented on components/onboarding/RichTextEditor.tsx
> +			<ScrollArea className="w-full h-full max-h-52">
I'm not sure about this. I've to look into it further. The `ScrollArea` was functioning correctly when I developed it, but now it’s not visible.

2024-10-27 17:04 UTC, pingSubhajit commented on components/onboarding/RichTextEditor.tsx
> +						className="min-h-40"
@sahilverma-dev @sourabhrathourr i think the padding is not the offender here as we want the text to start from the very left boundary of the text box. That would be the expected behaviour as we do not have a border around the textbox.

Whereas, i think the issue is that the list indicator is position itself as `outside` as it does by default. If we can edit the style of the lists in the text editor to position itself as `inside` by using the CSS rule `list-style-position: inside;` hopefully that should do the trick.

2024-10-27 17:09 UTC, sahilverma-dev commented
@pingSubhajit let me if there're any other changes?

2024-10-28 15:55 UTC, pingSubhajit requested changes
The bug mentioned below would be confusing to the users and it is crucial to fix it before we ship the component.

2024-10-28 15:55 UTC, pingSubhajit commented on components/onboarding/RichTextEditor.tsx
> +				<div className={cn('relative mb-2', className)}>
Also if you notice carefully in the attached video, the hover effect in the description field works on mouse enter but the line that appears on hover doesn't revert back on mouse leave unlike other input fields where the effect works without this problem. Please refer to the video for more information.

https://github.com/user-attachments/assets/6bccd313-ff40-44c8-a9c5-30cd79b6aed8

2024-10-28 16:03 UTC, sahilverma-dev commented
> The bug mentioned below would be confusing to the users and it is crucial to fix it before we ship the component.

Ok got it.

2024-10-30 06:59 UTC, sahilverma-dev commented
### Issue:
[LET-12 Simple rich text editor component for education & experience description](https://linear.app/letraz/issue/LET-12/feat-simple-rich-text-editor-component-for-education-and-experience)

### Description:
This PR introduces a new minimal rich text editor using Tiptap and Shadcn components, enhancing the content editing capabilities of the application. The old rich text editor code has been removed to streamline the codebase.

### Implemented Changes:
- Integrated Tiptap and Shadcn components for the new rich text editor.
- Resolve all isssues
- Removed the old code for the previous rich text editor.

### Closing Note:
This update adds a new minimal rich text editor while removing the old implementation. Please note that the switch component has a style conflict that needs to be resolved.

2024-10-30 06:59 UTC, sahilverma-dev commented on components/onboarding/RichTextEditor.tsx
> +				<div className={cn('relative mb-2', className)}>
This is resolved now

2024-10-30 06:59 UTC, sahilverma-dev commented on components/onboarding/RichTextEditor.tsx
> +			<ScrollArea className="w-full h-full max-h-52">
This is resolved now

2024-10-30 13:52 UTC, pingSubhajit commented on components/onboarding/RichTextEditor.tsx
> +						className="min-h-40"
Done, resolving the conversation

2024-11-01 03:58 UTC, pingSubhajit approved these changes
Changes look fine to me. The text editor functions as usual and design looks consistent with the visual direction of the application. I recommend merging it to the main branch.

2024-11-06 07:19 UTC, sahilverma-dev reviewed
Looking good

2024-11-23 15:10 UTC, sourabhrathourr approved these changes
It looks fine to me, we can merge it.

2024-11-23 15:11 UTC, merged