feat: functionality to remove added educations from the onboarding screen
pingSubhajit/letraz pull request #15
Opened 2024-10-24 06:21 UTC by sourabhrathourr

### Issue: 
[LET-10: feat: Functionality to remove added educations from the onboarding screen](https://linear.app/letraz/issue/LET-10/feat-functionality-to-remove-added-educations-from-the-onboarding)

### Description:
The current implementation of the onboarding page's education screen allows users to add multiple education histories but lacks the ability to remove previously added entries. This feature is necessary to enable users to correct or adjust their education information as needed.

### Changes Made:
- Added a "Remove" or "Delete" button/icon next to each added education entry.
- Implemented functionality to remove the corresponding education entry from the screen and user's data upon clicking the "Remove" or "Delete" button/icon.
- Ensured smooth UI updates to reflect the removal of the entry.
- Implemented proper data handling and error prevention mechanisms for the removal process.
- Tested the feature across all supported browsers and devices to ensure consistent functionality.

### Closing Note:
The functionality to remove added educations from the onboarding screen has been successfully implemented. Users can now easily correct or adjust their education information by removing previously added entries, ensuring accurate data collection during the onboarding process.

2024-10-24 14:23 UTC, sahilverma-dev approved these changes
Working fine

2024-10-24 16:34 UTC, pingSubhajit requested changes
Everything else looks fine. Just make the necessary changes and it will be good to merge.

2024-10-24 16:34 UTC, pingSubhajit commented on components/onboarding/Education.tsx
> +import PopConfirm from '../ui/pop-confirm'
Try importing the component using import alias instead of relative path

2024-10-25 09:02 UTC, sourabhrathourr commented on components/onboarding/Education.tsx
> +import PopConfirm from '../ui/pop-confirm'
Done 👍🏻

2024-10-25 10:39 UTC, pingSubhajit approved these changes
This looks fine now. I recommend merging.

2024-10-25 13:56 UTC, merged