feat: functionality to remove added past experiences from the onboarding screen
pingSubhajit/letraz pull request #16
Opened 2024-10-24 07:03 UTC by sourabhrathourr

### Issue:
[LET-11: feat: Functionality to remove added past experiences from the onboarding screen](https://linear.app/letraz/issue/LET-11/feat-functionality-to-remove-added-past-experiences-from-the)

### Description:
The current implementation of the onboarding page for adding past experiences lacks the ability for users to remove previously added entries. This feature is crucial for allowing users to correct or adjust their work history as needed.

### Changes Made:
- Added a "Remove"  icon next to each added past experience entry.
- Implemented functionality to remove the corresponding past experience entry from the screen and user's data upon clicking the "Remove" icon.
- Ensured smooth UI updates to reflect the removal of the entry.
- Handled the removal process correctly, preventing any data inconsistencies or errors.
- Tested the feature across all supported browsers and devices to ensure proper functionality.

### Closing Note:
The functionality to remove added past experiences from the onboarding screen has been successfully implemented. Users can now conveniently remove previously added entries, providing them with the ability to correct or adjust their work history as needed. The feature has been thoroughly tested and meets the acceptance criteria.

2024-10-24 15:26 UTC, sahilverma-dev approved these changes

2024-10-24 16:36 UTC, pingSubhajit requested changes
Everything else looks fine, just make the necessary changes and this'll be good to merge

2024-10-24 16:36 UTC, pingSubhajit commented on components/onboarding/Education.tsx
> +import PopConfirm from '../ui/pop-confirm'
Try importing using import alias instead of realative path

2024-10-24 16:36 UTC, pingSubhajit commented on components/onboarding/Experience.tsx
> +			{/* EXPERIENCES */}
Nice find, good job

2024-10-25 08:59 UTC, sourabhrathourr commented on components/onboarding/Education.tsx
> +import PopConfirm from '../ui/pop-confirm'
Yes, did that.

2024-10-25 09:00 UTC, sourabhrathourr commented on components/onboarding/Experience.tsx
> +			{/* EXPERIENCES */}
Haha, thanks.

2024-10-25 10:38 UTC, pingSubhajit approved these changes
Alright, this looks good. We can merge it

2024-10-25 13:58 UTC, merged