bug: Onboarding page next and prev button overlapping elements in low height displays
pingSubhajit/letraz pull request #21
Opened 2024-12-10 02:38 UTC by sahilverma-dev

### Issue:
[LET-13/bug-onboarding-page-next-and-prev-button-overlapping-elements-in-low](https://linear.app/letraz/issue/LET-13/bug-onboarding-page-next-and-prev-button-overlapping-elements-in-low)

### Description:
This issue addresses the overlapping of the "Next" and "Previous" buttons with other elements on the onboarding page when viewed on smaller screen sizes. The buttons were incorrectly positioned, causing visual issues and interfering with the user experience.

### Implemented Changes:
- Wrapped containers in ShadCN scroll area to ensure proper scrolling behavior and prevent overlap.
- Made the button containers fixed to maintain their position regardless of the content above or below.
- Fixed responsiveness issues related to button placement and layout for a smoother user experience across different screen sizes.

### Closing Note:
This update resolves the overlapping button issue on the onboarding page by making necessary layout adjustments. Additionally, a new minimal rich text editor was introduced to replace the old one. However, the switch component is experiencing a style conflict, which needs to be addressed in a future update.

2024-12-21 05:36 UTC, pingSubhajit requested changes
Hey @sahilverma-dev 

The buttons work for me although in the default state, there's a few issues that i have found.

1. First is that the previous button overlaps the rich text tools in the default view.
![image](https://github.com/user-attachments/assets/fc6dcf05-ef58-4235-b772-145d15c393b6)

2. Although the buttons work, a few page layouts have been changed in the process which should not be the case. Refer to the pictures attached. Please note that the left one is the before (how it should look) and the right one is the after (how it looks now).
![image](https://github.com/user-attachments/assets/d272dc13-66e3-48d9-b808-7bed2416a70e)
![image](https://github.com/user-attachments/assets/48391577-a426-4712-8bcf-f9dd27f26137)

Please take a look at these issues and revert back.

2024-12-24 05:33 UTC, sourabhrathourr requested changes
@sahilverma-dev The button works now as expected, and i'm facing no problem navigating the onboarding screens.

<img width="857" alt="image" src="https://github.com/user-attachments/assets/748cd248-c6da-4b46-9abf-d76edd882293" />

Only this personal details button is overlapping with the rich text editor. Fixing this, we'll good to merge this PR I think

2024-12-28 03:51 UTC, sahilverma-dev commented on components/providers/SmoothScrollProvider.tsx
> -			<main ref={content} className="h-full">
@pingSubhajit this code was the reason behind the scroll issue on form pages that's why i removed it and now after change this is causing issue for differnce in ui for as mentioned here.
https://github.com/pingSubhajit/letraz/pull/21#pullrequestreview-2518588850

2025-01-04 15:27 UTC, pingSubhajit approved these changes
Looks good to me. Let's go ahead and merge it.

2025-01-06 05:09 UTC, sourabhrathourr approved these changes
It looks good to me, we can proceed on to merge this.

2025-01-06 05:11 UTC, merged