feat: crud operations for projects
pingSubhajit/letraz pull request #22
Opened 2024-12-16 14:43 UTC by sourabhrathourr

### Issue:
[LET-18: feat: core: DB model and CRUD functionality for projects](https://linear.app/letraz/issue/LET-18/core-db-model-and-crud-functionality-for-projects)

### Description:
The objective of this issue is to establish the database model and implement the CRUD (Create, Read, Update, Delete) operations for managing projects within the application. This will enable users to create, view, modify, and delete their project entries, providing a comprehensive system for project data management.

### Changes Made:
- Defined the database model for projects, including the following fields:
  - Project Name (required, unique identifier)
  - Description (optional)
  - Technologies (optional, array of strings)
  - Role (required)
  - Accomplishments (optional, array of strings)
  - Links (optional, array of strings)
  - UserId (required, foreign key referencing the user)

- Implemented CRUD operations for projects:
  - Create: Allows users to create new project entries with required and optional fields.
  - Read: Retrieves a list of projects for a specific user.
  - Update: Enables users to modify existing project entries by updating any fields.
  - Delete: Allows users to remove project entries from their profile.

- Implemented data validation and error handling mechanisms to ensure data integrity and graceful handling of invalid or missing data.
- Implemented appropriate security measures, including user authentication and authorization, to protect project data from unauthorized access and ensure users can only access and modify their own project entries.

### Closing Note:
The database model for projects and the CRUD functionality have been successfully implemented, providing a robust system for managing project data within the application. Users can now create, view, update, and delete their project entries, ensuring a seamless experience for managing their project information.

2024-12-18 03:42 UTC, sahilverma-dev requested changes

2024-12-18 03:42 UTC, sahilverma-dev commented on components/resume/ResumeEditor.tsx
> +			await createProject(resume.userId, projectData)
Error handing for server actions:

refer this doc: https://nextjs.org/docs/app/building-your-application/routing/error-handling

2024-12-18 03:42 UTC, sahilverma-dev commented on components/resume/ResumeEditor.tsx
> +		try {
@pingSubhajit sir why are we not using tanstack query?

2024-12-18 03:42 UTC, sahilverma-dev commented on components/resume/ResumeEditor.tsx
> +											<FormLabel>Links</FormLabel>
disable form items while adding project and add loading indicator

2024-12-18 03:42 UTC, sahilverma-dev commented on components/resume/ResumeEditor.tsx
> +			await createProject(resume.userId, projectData)
and show toast for error and some loading indicator

2024-12-21 05:01 UTC, pingSubhajit commented on components/resume/ResumeEditor.tsx
> +		try {
Hmm... we actually can. And that would in fact make the asynchronous state management much more predictable. I recommend migrating to Tanstack Query. We'll run a migration after the open PRs are merged.

2024-12-21 05:17 UTC, pingSubhajit requested changes
Hey @sourabhrathourr 

While trying to add a new project through the ResumeEditor.tsx UI, i am running into a DB error in the server action. It says

`NeonDbError: malformed array literal: "Typescript, Supabase, PostgresQL, NextJS"`
```js
{
    severity: 'ERROR',
    code: '22P02',
    detail: 'Array value must start with "{" or dimension information.',
}
```

I put `Typescript, Supabase, PostgresQL, NextJS` in the technologies field.
Please take a look and revert back.

2025-01-04 15:00 UTC, sourabhrathourr commented on components/resume/ResumeEditor.tsx
> +			await createProject(resume.userId, projectData)
This won't be our final UI, the UI is just for testing.

2025-01-04 15:01 UTC, sourabhrathourr commented
> Hey @sourabhrathourr
> 
> While trying to add a new project through the ResumeEditor.tsx UI, i am running into a DB error in the server action. It says
> 
> `NeonDbError: malformed array literal: "Typescript, Supabase, PostgresQL, NextJS"`
> 
> ```js
> {
>     severity: 'ERROR',
>     code: '22P02',
>     detail: 'Array value must start with "{" or dimension information.',
> }
> ```
> 
> I put `Typescript, Supabase, PostgresQL, NextJS` in the technologies field. Please take a look and revert back.

This issue should be fixed now @pingSubhajit

2025-01-06 08:08 UTC, pingSubhajit commented
In the light of the new migration strategy to a dedicated backend service, see [LET-38](https://linear.app/letraz/issue/LET-38/core-migrate-existing-backend-functionality-from-nextjs-to-dedicated), this issue has been cancelled. The PR is being close in the response.

2025-01-06 08:08 UTC, closed without merging